"""empty message

Revision ID: a179c4e9a5a6
Revises: a5cffa318ac2
Create Date: 2025-02-14 17:57:10.642677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a179c4e9a5a6'
down_revision = 'a5cffa318ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('director',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=False),
    sa.Column('nacionalidad', sa.String(length=250), nullable=False),
    sa.Column('numero_peliculas', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('director')
    # ### end Alembic commands ###
